# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(968, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".user-icon > .v-responsive__sizer").click()
    self.driver.find_element(By.LINK_TEXT, "Iniciar sesión").click()
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "user").send_keys("admin@admin.com")
    self.driver.find_element(By.ID, "pass").send_keys("admin")
    self.driver.find_element(By.ID, "pass").send_keys(Keys.ENTER)
    element = self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) .v-responsive__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
