# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuy():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buy(self):
    self.driver.get("http://localhost:8080/")
    self.driver.set_window_size(968, 728)
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) .v-responsive__content").click()
    self.driver.find_element(By.ID, "user").send_keys("admin@admin.com")
    self.driver.find_element(By.ID, "pass").send_keys("admin")
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) .v-card__text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(3) .v-card__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".add-cart").click()
    self.driver.find_element(By.CSS_SELECTOR, ".cart-logo").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".cart-logo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".cart-logo")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(1)").click()
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("Avenida asociaciones de vecinos nº1 1ºB")
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("chahu@alum.us.es")
    self.driver.find_element(By.ID, "email").send_keys(Keys.ENTER)
    self.driver.find_element(By.ID, "cardNumber").send_keys("4242 4242 4242 4242")
    self.driver.find_element(By.ID, "cardExpiry").send_keys("12 / 30")
    self.driver.find_element(By.ID, "cardCvc").send_keys("123")
    self.driver.find_element(By.ID, "billingName").send_keys("Chao Hu")
    self.driver.find_element(By.CSS_SELECTOR, ".SubmitButton-IconContainer").click()
  
